import {
  Gauge,
  ArrowDownUp,
  Scale,
  Zap,
  ArrowRightLeft,
  Orbit,
  Droplets,
  Thermometer,
  Waves,
  Sun,
  Sparkles,
  Plug,
  Magnet,
  Atom,
  type LucideIcon,
} from "lucide-react";

export const TOPIC_ICONS: Record<string, LucideIcon> = {
  cinematica: Gauge,
  dinamica: ArrowDownUp,
  estatica: Scale,
  "trabalho-energia": Zap,
  "impulso-momento": ArrowRightLeft,
  gravitacao: Orbit,
  hidrostatica: Droplets,
  termologia: Thermometer,
  ondulatoria: Waves,
  optica: Sun,
  eletrostatica: Sparkles,
  eletrodinamica: Plug,
  eletromagnetismo: Magnet,
  "fisica-moderna": Atom,
};
